/**
Copyright (c) 2019-present Lenovo
Licensed under BSD-3, see COPYING.BSD file for details."
**/   

#ifndef _FACE_UI_DEFINE_H_
#define _FACE_UI_DEFINE_H_

////////////////////////////COMMON DEFINE////////////////////////////////////////
#define		LOGO_BOTTOM				50
#define		LOGO_WIDTH				100
#define		LOGO_HEIGHT				300

#define		LIST_SPAN				26
#define		BITMAP_SIZE				16  //todo

#define		PROGRESS_FILL_SPAN			7
#define		PROGRESS_FILL_HEIGHT		20
#define		PROGRESS_HEIGHT				34

#define		PROGRESS_FILL_HEAD_WIDTH	10
#define		PROGRESS_FILL_HEAD_HEIGHT	PROGRESS_FILL_HEIGHT

#define		PROGRESS_FILL_TAIL_WIDTH	10
#define		PROGRESS_FILL_TAIL_HEIGHT	PROGRESS_FILL_HEIGHT

#define		PROGRESS_FILL_FRAME_HEAD_WIDTH	20
#define		PROGRESS_FILL_FRAME_HEAD_HEIGHT	PROGRESS_HEIGHT

#define		PROGRESS_FILL_FRAME_TAIL_WIDTH	20
#define		PROGRESS_FILL_FRAME_TAIL_HEIGHT	PROGRESS_HEIGHT

#define		TITLEBOX_LEFT			46
#define		TITLEBOX_HEIGHT			90
#define		TITLEBOX_TEXT_HEIGHT	30

//White background
//#define	SEL_BK_PAR_BG_LEFT				54	//calc
#define		WHITE_BG_TOP						552	
#define		WHITE_BG_WIDTH						2160
#define		WHITE_BG_HEIGHT						1290
#define		WHITE_BG_CORNER_SIZE				30

#define		BACKUP_BUTTON_LEFT					64
#define		BACKUP_BUTTON_TOP					54
#define		BACKUP_BUTTON_SIZE					84


////////////////////////////MAIN PAGE DEFINE////////////////////////////////////
#define		MAIN_PAGE_TITLE_TOP					306
//#define		MAIN_PAGE_TITLE_LEFT				840
#define		MAIN_PAGE_TITLE_WIDTH				1158
#define		MAIN_PAGE_TITLE_HEIGHT				140

#define		MAIN_PAGE_EXIT_BTN_WIDTH			80
#define		MAIN_PAGE_EXIT_BTN_HEIGHT			80
#define		MAIN_PAGE_EXIT_BTN_TOP				46
#define		MAIN_PAGE_EXIT_BTN_RIGHT			60

#define		MAIN_PAGE_SPAN_EXIT_ABOUT_BTN		30

#define		MAIN_PAGE_ABOUT_BTN_WIDTH			80
#define		MAIN_PAGE_ABOUT_BTN_HEIGHT			80
#define		MAIN_PAGE_ABOUT_BTN_TOP				MAIN_PAGE_EXIT_BTN_TOP
#define		MAIN_PAGE_ABOUT_BTN_RIGHT			(MAIN_PAGE_EXIT_BTN_RIGHT + MAIN_PAGE_SPAN_EXIT_ABOUT_BTN + MAIN_PAGE_EXIT_BTN_WIDTH)

#define		MAIN_PAGE_BACK_ICON_WIDTH			700
#define		MAIN_PAGE_BACK_ICON_HEIGHT			MAIN_PAGE_BACK_ICON_WIDTH
#define		MAIN_PAGE_BACK_ICON_LEFT			1082
#define		MAIN_PAGE_BACK_ICON_BOTTOM			700

#define		MAIN_PAGE_RECOVERY_ICON_WIDTH		MAIN_PAGE_BACK_ICON_WIDTH
#define		MAIN_PAGE_RECOVERY_ICON_HEIGHT		MAIN_PAGE_BACK_ICON_HEIGHT
#define		MAIN_PAGE_RECOVERY_ICON_RIGHT		1082
#define		MAIN_PAGE_RECOVERY_ICON_BOTTOM		MAIN_PAGE_BACK_ICON_BOTTOM

#define		MAIN_PAGE_SPAN_BACK_RECOVERY		276

#define		MAIN_PAGE_INFO_TEXT_TOP				440

#define		MAIN_PAGE_INFO_BOTTOM				390
#define		MAIN_PAGE_INFO_WIDTH				1498
#define		MAIN_PAGE_INFO_HEIGHT				40


////////////////////////////Msg Box////////////////////////////////////
#define MSG_BOX_WIDTH			1080
#define MSG_BOX_HEIGHT			500

#define MSG_TYPE_ICON_TOP		50
#define MSG_TYPE_ICON_LEFT		50
#define MSG_TYPE_ICON_SIZE		52

#define MSG_SPAN_TYPE_TITLE		20
#define MSG_TITLE_TEXT_LEFT		(MSG_TYPE_ICON_LEFT + MSG_TYPE_ICON_SIZE + MSG_SPAN_TYPE_TITLE)

#define MSG_CLOSE_BTN_TOP		50
#define MSG_CLOSE_BTN_RIGHT		50
#define MSG_CLOSE_BTN_SIZE		30

#define MSG_TEXT_LEFT			70
#define MSG_TEXT_TOP			(MSG_TYPE_ICON_SIZE + MSG_TYPE_ICON_TOP + 20)
#define MSG_TEXT_HEIGHT			120   //TODO

#define MSG_TEXT_AREA_WIDTH		(MSG_BOX_WIDTH - 70 - 70)
#define MSG_TEXT_AREA_HEIGHT	(MSG_BOX_HEIGHT - 130 - 180)	
#define MSG_TEXT_LINE_SPACE		8

#define MSG_SPLIT_LINE_TOP		(MSG_BOX_HEIGHT - 150 - 1)

#define MSG_BTN_RIGHT			50
#define MSG_BTN_BOTTOM			32
#define MSG_BTN_TOP				(MSG_SPLIT_LINE_TOP + 1 + 28)
#define MSG_BTN_WIDTH			224
#define MSG_BTN_HEIGHT			92
#define MSG_BTN_SPAN			30

////////////////////////////Multi Msg Box////////////////////////////////////
#define MULTI_MSG_BOX_WIDTH			1080
#define MULTI_MSG_BOX_HEIGHT		700
#define MULTI_MSG_TEXT_TOP				(30 + MSG_TYPE_ICON_SIZE + MSG_TYPE_ICON_TOP + 20)

#define MULTI_MSG_TEXT_AREA_WIDTH		(MULTI_MSG_BOX_WIDTH - 70 - 70)
#define MULTI_MSG_TEXT_AREA_HEIGHT		(MULTI_MSG_BOX_HEIGHT - 130 - 180)	
#define MULTI_MSG_TEXT_LINE_SPACE		25
#define MULTI_MSG_TEXT_HEIGHT			330

#define MULTI_MSG_SPLIT_LINE_TOP		(MULTI_MSG_BOX_HEIGHT - 150 - 1)

#define MULTI_MSG_BTN_TOP				(MULTI_MSG_SPLIT_LINE_TOP + 1 + 28)

////////////////////////////Two line Msg Box////////////////////////////////////
#define TWO_LINE_MSG_BOX_WIDTH			1080
#define TWO_LINE_MSG_BOX_HEIGHT			550
#define TWO_LINE_MSG_TEXT_TOP			(MSG_TYPE_ICON_SIZE + MSG_TYPE_ICON_TOP + 30)

#define MSG_TEXT_AREA_HEIGHT_EX			(TWO_LINE_MSG_BOX_HEIGHT - 130 - 180)
#define MSG_TEXT_LINE_SPACE_EX			14

#define MSG_SPLIT_LINE_TOP_EX			(TWO_LINE_MSG_BOX_HEIGHT - 150 - 1)

#define TWO_LINE_MSG_TEXT_AREA_WIDTH		(TWO_LINE_MSG_BOX_WIDTH - 70 - 70)
#define TWO_LINE_MSG_TEXT_AREA_HEIGHT		(TWO_LINE_MSG_BOX_HEIGHT - 130 - 180)	
#define TWO_LINE_MSG_TEXT_LINE_SPACE		8

/////////////////////////////////////////Wait Msg Face//////////////////////////////////////////////////////////
#define WAIT_MSG_WIDTH			1149
#define WAIT_MSG_HEIGHT			258
#define WAIT_MSG_TEXT_WIDTH		730
#define WAIT_MSG_TEXT_HEIGHT	48

/////////////////////////////////////////Select Backup Part Face//////////////////////////////////////////////////////////
//#define SEL_BK_PAR_TITLE_LEFT					54  //calc
#define SEL_BK_PAR_TITLE_TOP					MAIN_PAGE_TITLE_TOP
#define SEL_BK_PAR_TITLE_WIDTH					975
#define SEL_BK_PAR_TITLE_HEIGHT					140

#define SEL_BK_PAR_SEL_POS_TEXT_TOP				(WHITE_BG_TOP + 50)
#define SEL_BK_PAR_SEL_POS_TEXT_LEFT			50
#define SEL_BK_PAR_SEL_POS_TEXT_WIDTH			54
#define SEL_BK_PAR_SEL_POS_TEXT_HEIGHT			54

#define SEL_BK_PAR_DISK_LIST_SCROL_SPACE		13
#define SEL_BK_PAR_DISK_LIST_TOP				(153 + WHITE_BG_TOP)
#define SEL_BK_PAR_DISK_LIST_LEFT				50
#define SEL_BK_PAR_DISK_LIST_WIDTH				(518 + SEL_BK_PAR_DISK_LIST_SCROL_SPACE)
#define SEL_BK_PAR_DISK_LIST_HEIGHT				718

#define SEL_BK_PAR_DISK_ITEM_SPAN				30
#define SEL_BK_PAR_DISK_ITEM_WIDTH				518
#define SEL_BK_PAR_DISK_ITEM_HEIGHT				147


#define SEL_BK_PAR_DISK_ITEM_ICON_SPAN			30
#define SEL_BK_PAR_DISK_ITEM_ICON_LEFT			SEL_BK_PAR_DISK_ITEM_ICON_SPAN
#define SEL_BK_PAR_DISK_ITEM_ICON_WIDTH			64
#define SEL_BK_PAR_DISK_ITEM_ICON_HEIGHT		98

#define SEL_BK_PAR_DISK_ITEM_TEXT_LEFT			(35 + SEL_BK_PAR_DISK_ITEM_ICON_WIDTH + SEL_BK_PAR_DISK_ITEM_ICON_LEFT)
#define SEL_BK_PAR_DISK_ITEM_TEXT_SPAN			20
#define SEL_BK_PAR_DISK_ITEM_TEXT_WIDTH			(SEL_BK_PAR_DISK_ITEM_WIDTH - SEL_BK_PAR_DISK_ITEM_ICON_SPAN - SEL_BK_PAR_DISK_ITEM_TEXT_LEFT - 20)
#define SEL_BK_PAR_DISK_ITEM_TEXT_HEIGHT		30

#define SEL_REC_POS_SCROLL_WIDTH				26

#define SEL_BK_PAR_PART_LIST_HEAD_TOP			(153 + WHITE_BG_TOP)
#define SEL_BK_PAR_PART_LIST_HEAD_LEFT			(SEL_BK_PAR_DISK_LIST_LEFT + SEL_BK_PAR_DISK_LIST_WIDTH + 52)
#define SEL_BK_PAR_PART_LIST_HEAD_WIDTH			1490
#define SEL_BK_PAR_PART_LIST_HEAD_HEIGHT		90

//#define SEL_BK_PAR_LIST_HEAD_TEXT_WIDTH			2160
//#define SEL_BK_PAR_LIST_HEAD_TEXT_HEIGHT		30

//#define SEL_BK_PAR_LIST_HEAD_TEXT_TOP					(SEL_BK_PAR_PART_LIST_HEAD_TOP + (SEL_BK_PAR_PART_LIST_HEAD_HEIGHT - SEL_BK_PAR_LIST_HEAD_TEXT_HEIGHT) / 2)
//#define SEL_BK_PAR_LIST_HEAD_TEXT_VOLUME_LEFT			667 
//#define SEL_BK_PAR_LIST_HEAD_TEXT_TYPE_LEFT				1220
//#define SEL_BK_PAR_LIST_HEAD_TEXT_TOTAL_SIZE_LEFT		1615
//#define SEL_BK_PAR_LIST_HEAD_TEXT_REMAIn_SIZE_LEFT		1935


#define SEL_BK_PAR_PART_LIST_TOP				(SEL_BK_PAR_PART_LIST_HEAD_TOP + SEL_BK_PAR_PART_LIST_HEAD_HEIGHT)
#define SEL_BK_PAR_PART_LIST_LEFT				(SEL_BK_PAR_DISK_LIST_LEFT + SEL_BK_PAR_DISK_LIST_WIDTH + 52)
#define SEL_BK_PAR_PART_LIST_WIDTH				(1490 - SEL_REC_POS_SCROLL_WIDTH)
#define SEL_BK_PAR_PART_LIST_HEIGHT				(718 - SEL_BK_PAR_PART_LIST_HEAD_HEIGHT)

#define SEL_BK_PAR_SCROLL_WIDTH					26
//#define SEL_BK_PAR_SCROLL_HEIGHT				SEL_BK_PAR_PART_LIST_HEIGHT

#define SEL_BK_PAR_DISK_LIST_PART_LIST_SPAN		52

#define SEL_BK_PAR_PART_ITEM_WIDTH				1446
#define SEL_BK_PAR_PART_ITEM_HEIGHT				100

#define SEL_BK_PAR_NAME_TEXT_LEFT				77
#define SEL_BK_PAR_NAME_TEXT_TOP				(102 + SEL_BK_PAR_PART_LIST_HEIGHT + SEL_BK_PAR_PART_LIST_TOP + 20)

#define SEL_BK_PAR_NAME_EDITBOX_LEFT			227 
#define SEL_BK_PAR_NAME_EDITBOX_TOP				(102 + SEL_BK_PAR_PART_LIST_HEIGHT + SEL_BK_PAR_PART_LIST_TOP)
#define SEL_BK_PAR_NAME_EDITBOX_WIDTH			980
#define SEL_BK_PAR_NAME_EDITBOX_HEIGHT			80

#define SEL_BK_PAR_NAME_EDITBOX_BK_SIZE_TEXT_SPAN		50

#define SEL_BK_PAR_BK_SIZE_TEXT_LEFT			(SEL_BK_PAR_NAME_EDITBOX_LEFT + SEL_BK_PAR_NAME_EDITBOX_WIDTH + SEL_BK_PAR_NAME_EDITBOX_BK_SIZE_TEXT_SPAN) 
#define SEL_BK_PAR_BK_SIZE_TEXT_TOP				(SEL_BK_PAR_NAME_EDITBOX_TOP + 20)
#define SEL_BK_PAR_BK_SIZE_TEXT_WIDTH			290

//#define SEL_BK_PAR_BK_SIZE_VALUE_LEFT			(SEL_BK_PAR_NAME_EDITBOX_LEFT + SEL_BK_PAR_NAME_EDITBOX_WIDTH + SEL_BK_PAR_NAME_EDITBOX_BK_SIZE_TEXT_SPAN + SEL_BK_PAR_BK_SIZE_TEXT_WIDTH + 20) 
//#define SEL_BK_PAR_BK_SIZE_VALUE_TOP			SEL_BK_PAR_BK_SIZE_TEXT_TOP

#define SEL_BK_PAR_INFO_TEXT_LEFT				82
#define SEL_BK_PAR_INFO_TEXT_BOTTOM				120
#define SEL_BK_PAR_INFO_TEXT_WIDTH				650

#define SEL_BK_PAR_INFO_PAR_TEXT_LEFT			82
#define SEL_BK_PAR_INFO_PAR_TEXT_BOTTOM			SEL_BK_PAR_INFO_TEXT_BOTTOM

#define SEL_BK_PAR_INFO_TEXT_SPAN				40

#define SEL_BK_PAR_BK_BUTTON_RIGHT				50 
#define SEL_BK_PAR_BK_BUTTON_TOP				(263 + SEL_BK_PAR_PART_LIST_HEIGHT + SEL_BK_PAR_PART_LIST_TOP)
#define SEL_BK_PAR_BK_BUTTON_WIDTH				424
#define SEL_BK_PAR_BK_BUTTON_HEIGHT				92 


////////////////////////////////////////Backup Face////////////////////////////////////
#define	BK_PAGE_TITLE_TOP					MAIN_PAGE_TITLE_TOP
//#define	BK_PAGE_TITLE_LEFT					840
#define	BK_PAGE_TITLE_WIDTH					980
#define	BK_PAGE_TITLE_HEIGHT				140

//#define BK_PAGE_TITLE_LEFT				54  //calc
#define BK_PAGE_SUB_TITLE_TOP				(WHITE_BG_TOP + 282)
#define BK_PAGE_SUB_TITLE_WIDTH				535
#define BK_PAGE_SUB_TITLE_HEIGHT			87

//#define BK_PAGE_REAMIN_TIME_TEXT_LEFT		87  //calc
#define BK_PAGE_REAMIN_TIME_TEXT_TOP		(175 + BK_PAGE_SUB_TITLE_TOP + BK_PAGE_SUB_TITLE_HEIGHT)
#define BK_PAGE_REAMIN_TIME_TEXT_WIDTH		185
#define BK_PAGE_REAMIN_TIME_TEXT_HEIGHT		39

//#define BK_PAGE_REAMIN_TIME_VALUE_LEFT	87  //calc
#define BK_PAGE_REAMIN_TIME_VALUE_TOP		BK_PAGE_REAMIN_TIME_TEXT_TOP
#define BK_PAGE_REAMIN_TIME_VALUE_WIDTH		130
#define BK_PAGE_REAMIN_TIME_VALUE_HEIGHT	39

#define BK_PAGE_REAMIN_TIME_TEXT_VALUE_SPAN		20

//#define BK_PAGE_PROGRESS_LEFT	87			//calc
#define BK_PAGE_PROGRESS_TOP				(78 + BK_PAGE_REAMIN_TIME_TEXT_TOP + BK_PAGE_REAMIN_TIME_TEXT_HEIGHT)
#define BK_PAGE_PROGRESS_WIDTH				1554

//#define BK_PAGE_INFO_LEFT	87  //calc
#define BK_PAGE_INFO_TOP					(277 + BK_PAGE_PROGRESS_TOP + PROGRESS_HEIGHT)
#define BK_PAGE_INFO_WIDTH					400
#define BK_PAGE_INFO_HEIGHT					30

//#define BK_PAGE_INFO_TEXT_LEFT	87  //calc
#define BK_PAGE_INFO_TEXT_TOP				(55 + BK_PAGE_INFO_TOP + BK_PAGE_INFO_HEIGHT)
#define BK_PAGE_INFO_TEXT_WIDTH				256
#define BK_PAGE_INFO_TEXT_HEIGHT			30

/////////////////////////////////////////Select Recovery Point Face//////////////////////////////////////////////////////////
//#define SEL_REC_POINT_TITLE_LEFT				54  //calc
#define SEL_REC_POINT_TITLE_TOP					MAIN_PAGE_TITLE_TOP
#define SEL_REC_POINT_TITLE_WIDTH				975
#define SEL_REC_POINT_TITLE_HEIGHT				140

#define SEL_REC_POINT_SEL_POS_TEXT_TOP			(WHITE_BG_TOP + 50)
#define SEL_REC_POINT_SEL_POS_TEXT_LEFT			50
#define SEL_REC_POINT_SEL_POS_TEXT_RIGHT		50
#define SEL_REC_POINT_SEL_POS_TEXT_WIDTH		54
#define SEL_REC_POINT_SEL_POS_TEXT_HEIGHT		54

#define SEL_REC_POINT_LIST_HEAD_TOP				(153 + WHITE_BG_TOP)
#define SEL_REC_POINT_LIST_HEAD_LEFT			50
#define SEL_REC_POINT_LIST_HEAD_WIDTH			2060
#define SEL_REC_POINT_LIST_HEAD_HEIGHT			90

//#define SEL_REC_POINT_LIST_HEAD_TEXT_WIDTH			2160
//#define SEL_REC_POINT_LIST_HEAD_TEXT_HEIGHT			30
//
//#define SEL_REC_POINT_LIST_HEAD_TEXT_TOP			(SEL_REC_POINT_LIST_HEAD_TOP + (SEL_REC_POINT_LIST_HEAD_HEIGHT - SEL_REC_POINT_LIST_HEAD_TEXT_HEIGHT) / 2)
//#define SEL_REC_POINT_LIST_HEAD_TEXT_POS_LEFT		(SEL_REC_POINT_LIST_HEAD_LEFT + 140)
//#define SEL_REC_POINT_LIST_HEAD_TEXT_TIME_LEFT		(SEL_REC_POINT_LIST_HEAD_LEFT + 780)
//#define SEL_REC_POINT_LIST_HEAD_TEXT_SIZE_LEFT		(SEL_REC_POINT_LIST_HEAD_LEFT + 1600)

#define SEL_REC_POINT_LIST_SCROLL_WIDTH				26

#define SEL_REC_POINT_LIST_TOP					(1 + SEL_REC_POINT_LIST_HEAD_TOP + SEL_REC_POINT_LIST_HEAD_HEIGHT)
#define SEL_REC_POINT_LIST_LEFT					50
#define SEL_REC_POINT_LIST_WIDTH				(2060 - SEL_REC_POINT_LIST_SCROLL_WIDTH)
#define SEL_REC_POINT_LIST_HEIGHT				(912 - SEL_REC_POINT_LIST_HEAD_HEIGHT)

#define SEL_REC_POINT_ICON_WIDTH				49
#define SEL_REC_POINT_ICON_HEIGHT				41

#define SEL_REC_POINT_ICON_TEXT_LEFT			39

#define SEL_REC_POINT_LOCK_ICON_WIDTH			25
#define SEL_REC_POINT_LOCK_ICON_HEIGHT			30 

#define SEL_REC_POINT_LOCK_ICON_TEXT_LEFT		22

#define SEL_REC_POINT_LIST_ITEM_WIDTH			2011	
#define SEL_REC_POINT_LIST_ITEM_HEIGHT			100	

#define SEL_REC_POINT_REC_BUTTON_RIGHT			50 
#define SEL_REC_POINT_REC_BUTTON_TOP			(63 + SEL_REC_POINT_LIST_HEIGHT + SEL_REC_POINT_LIST_TOP)
#define SEL_REC_POINT_REC_BUTTON_WIDTH			420
#define SEL_REC_POINT_REC_BUTTON_HEIGHT			92

#define SEL_REC_POINT_DEL_BUTTON_LEFT			1194
#define SEL_REC_POINT_DEL_BUTTON_TOP			SEL_REC_POINT_REC_BUTTON_TOP 
#define SEL_REC_POINT_DEL_BUTTON_WIDTH			420
#define SEL_REC_POINT_DEL_BUTTON_HEIGHT			92

#define SEL_REC_POINT_BUTTON_SPAN				76

#define SEL_REC_POINT_INFO_TEXT_TOP				(SEL_REC_POINT_LIST_HEIGHT + SEL_REC_POINT_LIST_TOP)
#define SEL_REC_POINT_INFO_TEXT_LEFT			SEL_REC_POINT_LIST_LEFT
#define SEL_REC_POINT_INFO_TEXT_WIDTH			2060  //(SEL_REC_POINT_DEL_BUTTON_LEFT - 150)
#define SEL_REC_POINT_INFO_TEXT_HEIGHT			120


/////////////////////////////////////////Select Recovery Positions (NEW DISK)//////////////////////////////////////////////////////////
//#define SEL_REC_POS_TITLE_LEFT					50
#define SEL_REC_POS_TITLE_TOP					MAIN_PAGE_TITLE_TOP
#define SEL_REC_POS_TITLE_WIDTH					975
#define SEL_REC_POS_TITLE_HEIGHT				140

#define SEL_REC_POS_SEL_POS_TEXT_TOP			(WHITE_BG_TOP + 50)
#define SEL_REC_POS_SEL_POS_TEXT_LEFT			50
#define SEL_REC_POS_SEL_POS_TEXT_RIGHT			50
#define SEL_REC_POS_SEL_POS_TEXT_WIDTH			54
#define SEL_REC_POS_SEL_POS_TEXT_HEIGHT			54

#define SEL_REC_POS_LIST_SCROLL_WIDTH			26

//#define SEL_REC_POS_LIST_TOP					(153 + WHITE_BG_TOP)
//#define SEL_REC_POS_LIST_LEFT					50
//#define SEL_REC_POS_LIST_WIDTH					(2060 - SEL_REC_POS_LIST_SCROLL_WIDTH)
//#define SEL_REC_POS_LIST_HEIGHT					912		

#define SEL_REC_POS_LIST_HEAD_TOP				(153 + WHITE_BG_TOP)
#define SEL_REC_POS_SEL_REC_POS_LIST_HEAD_LEFT			50
#define SEL_REC_POS_LIST_HEAD_WIDTH			2060
#define SEL_REC_POS_LIST_HEAD_HEIGHT			90

#define SEL_REC_POS_LIST_SCROLL_WIDTH			26

#define SEL_REC_POS_LIST_TOP					(1 + SEL_REC_POS_LIST_HEAD_TOP + SEL_REC_POS_LIST_HEAD_HEIGHT)
#define SEL_REC_POS_LIST_LEFT					50
#define SEL_REC_POS_LIST_WIDTH					(2060 - SEL_REC_POS_LIST_SCROLL_WIDTH)
#define SEL_REC_POS_LIST_HEIGHT					(912 - SEL_REC_POS_LIST_HEAD_HEIGHT)

#define SEL_REC_POS_LIST_ITEM_WIDTH				2011	
#define SEL_REC_POS_LIST_ITEM_HEIGHT			100	

#define SEL_REC_POS_ICON_WIDTH					73
#define SEL_REC_POS_ICON_HEIGHT					64

#define SEL_REC_POS_ICON_TEXT_LEFT				39

#define SEL_REC_POS_LIST_ITEM_WIDTH				2011	
#define SEL_REC_POS_LIST_ITEM_HEIGHT			100	

#define SEL_REC_POS_NEXT_BUTTON_RIGHT			50 
#define SEL_REC_POS_NEXT_BUTTON_TOP				(63 + SEL_REC_POS_LIST_HEIGHT + SEL_REC_POS_LIST_TOP)
#define SEL_REC_POS_NEXT_BUTTON_WIDTH			420
#define SEL_REC_POS_NEXT_BUTTON_HEIGHT			92

////////////////////////////////////////Recovery Face////////////////////////////////////
#define	REC_PAGE_TITLE_TOP					MAIN_PAGE_TITLE_TOP
//#define	REC_PAGE_TITLE_LEFT				840
#define	REC_PAGE_TITLE_WIDTH				980
#define	REC_PAGE_TITLE_HEIGHT				140

//#define REC_PAGE_TITLE_LEFT				54  //calc
#define REC_PAGE_SUB_TITLE_TOP				(WHITE_BG_TOP + 282)
#define REC_PAGE_SUB_TITLE_WIDTH			535
#define REC_PAGE_SUB_TITLE_HEIGHT			87

//#define REC_PAGE_REAMIN_TIME_TEXT_LEFT	87  //calc
#define REC_PAGE_REAMIN_TIME_TEXT_TOP		(175 + REC_PAGE_SUB_TITLE_TOP + REC_PAGE_SUB_TITLE_HEIGHT)
#define REC_PAGE_REAMIN_TIME_TEXT_WIDTH		185
#define REC_PAGE_REAMIN_TIME_TEXT_HEIGHT	39

//#define REC_PAGE_REAMIN_TIME_VALUE_LEFT	87  //calc
#define REC_PAGE_REAMIN_TIME_VALUE_TOP		REC_PAGE_REAMIN_TIME_TEXT_TOP
#define REC_PAGE_REAMIN_TIME_VALUE_WIDTH	130
#define REC_PAGE_REAMIN_TIME_VALUE_HEIGHT	39

#define REC_PAGE_REAMIN_TIME_TEXT_VALUE_SPAN		20

//#define REC_PAGE_PROGRESS_LEFT	87			//calc
#define REC_PAGE_PROGRESS_TOP				(78 + REC_PAGE_REAMIN_TIME_TEXT_TOP + REC_PAGE_REAMIN_TIME_TEXT_HEIGHT)
#define REC_PAGE_PROGRESS_WIDTH				1554

//#define REC_PAGE_INFO_LEFT	87  //calc
#define REC_PAGE_INFO_TOP					(277 + REC_PAGE_PROGRESS_TOP + PROGRESS_HEIGHT)
#define REC_PAGE_INFO_WIDTH					550
#define REC_PAGE_INFO_HEIGHT				30

//#define REC_PAGE_INFO_TEXT_LEFT	87  //calc
#define REC_PAGE_INFO_TEXT_TOP				(55 + REC_PAGE_INFO_TOP + REC_PAGE_INFO_HEIGHT)
#define REC_PAGE_INFO_TEXT_WIDTH			256
#define REC_PAGE_INFO_TEXT_HEIGHT			30


////////////////////////////////////////Recover Complete UI Msg box/////////////////////////////////////////////////////////////
#define COMPLETE_MSG_WIDTH						1074
#define COMPLETE_MSG_HEIGHT						478

#define COMPLETE_MSG_CLOSE_BTN_TOP				54
#define COMPLETE_MSG_CLOSE_BTN_RIGHT			50
#define COMPLETE_MSG_CLOSE_BTN_WIDTH			30
#define COMPLETE_MSG_CLOSE_BTN_HEIGHT			30

#define COMPLETE_MSG_INFO_ICON_TOP				174
#define COMPLETE_MSG_INFO_ICON_LEFT				370
#define COMPLETE_MSG_INFO_ICON_WIDTH			68
#define COMPLETE_MSG_INFO_ICON_HEIGHT			68

#define COMPLETE_MSG_TEXT_TOP					COMPLETE_MSG_INFO_ICON_TOP
#define COMPLETE_MSG_TEXT_LEFT					(COMPLETE_MSG_INFO_ICON_LEFT + COMPLETE_MSG_INFO_ICON_WIDTH + 30)
#define COMPLETE_MSG_TEXT_WIDTH					240
#define COMPLETE_MSG_TEXT_HEIGHT				60

#define COMPLETE_MSG_SPLIT_LINE_TOP				340
#define COMPLETE_MSG_SPLIT_LINE_LEFT			0
#define COMPLETE_MSG_SPLIT_LINE_WIDTH			(COMPLETE_MSG_WIDTH - 4)
#define COMPLETE_MSG_SPLIT_LINE_HEIGHT			1

#define COMPLETE_MSG_CONFIRM_BTN_TOP			(COMPLETE_MSG_SPLIT_LINE_TOP + 26)
#define COMPLETE_MSG_CONFIRM_BTN_LEFT			803
#define COMPLETE_MSG_CONFIRM_BTN_WIDTH			220
#define COMPLETE_MSG_CONFIRM_BTN_HEIGHT			92


////////////////////////////////////////Recover Complete UI Msg box with message/////////////////////////////////////////////////////////////
#define COMPLETE_MSG_EX_WIDTH						1074
#define COMPLETE_MSG_EX_HEIGHT						522

#define COMPLETE_MSG_EX_CLOSE_BTN_TOP				54
#define COMPLETE_MSG_EX_CLOSE_BTN_RIGHT				50
#define COMPLETE_MSG_EX_CLOSE_BTN_WIDTH				30
#define COMPLETE_MSG_EX_CLOSE_BTN_HEIGHT			30

#define COMPLETE_MSG_EX_INFO_ICON_TOP				121
#define COMPLETE_MSG_EX_INFO_ICON_LEFT				370
#define COMPLETE_MSG_EX_INFO_ICON_WIDTH				68
#define COMPLETE_MSG_EX_INFO_ICON_HEIGHT			68

#define COMPLETE_MSG_EX_TEXT_TOP					COMPLETE_MSG_EX_INFO_ICON_TOP
#define COMPLETE_MSG_EX_TEXT_LEFT					(COMPLETE_MSG_EX_INFO_ICON_LEFT + COMPLETE_MSG_EX_INFO_ICON_WIDTH + 30)
#define COMPLETE_MSG_EX_TEXT_WIDTH					240
#define COMPLETE_MSG_EX_TEXT_HEIGHT					60

#define COMPLETE_MSG_EX_MSG_TEXT_TOP				(COMPLETE_MSG_EX_TEXT_TOP + COMPLETE_MSG_EX_TEXT_HEIGHT + 58)
#define COMPLETE_MSG_EX_MSG_TEXT_LEFT				70   //TODO
//#define COMPLETE_MSG_EX_MSG_TEXT_WIDTH			240
#define COMPLETE_MSG_EX_MSG_TEXT_HEIGHT				80

#define COMPLETE_MSG_EX_SPLIT_LINE_TOP				(COMPLETE_MSG_EX_MSG_TEXT_TOP +  + 132)
#define COMPLETE_MSG_EX_SPLIT_LINE_LEFT				0
#define COMPLETE_MSG_EX_SPLIT_LINE_WIDTH			(COMPLETE_MSG_EX_WIDTH - 4)
#define COMPLETE_MSG_EX_SPLIT_LINE_HEIGHT			1

#define COMPLETE_MSG_EX_CONFIRM_BTN_TOP				(COMPLETE_MSG_EX_SPLIT_LINE_TOP + 28)
#define COMPLETE_MSG_EX_CONFIRM_BTN_LEFT			803
#define COMPLETE_MSG_EX_CONFIRM_BTN_WIDTH			220
#define COMPLETE_MSG_EX_CONFIRM_BTN_HEIGHT			92

////////////////////////////////////////About box/////////////////////////////////////////////////////////////
#define		ABOUT_PAGE_TITLE_TOP				306
#define		ABOUT_PAGE_TITLE_LEFT				840
#define		ABOUT_PAGE_TITLE_WIDTH				1158
#define		ABOUT_PAGE_TITLE_HEIGHT				140

#define		ABOUT_PAGE_SUB_TITLE_LEFT				50
#define		ABOUT_PAGE_SUB_TITLE_TOP				(WHITE_BG_TOP + 50)
#define		ABOUT_PAGE_SUB_TITLE_WIDTH				535
#define		ABOUT_PAGE_SUB_TITLE_HEIGHT				87

#define		ABOUT_PAGE_TAB_SPAN						107

#define		ABOUT_PAGE_TAB_INTRODUCE_TOP			(47 + ABOUT_PAGE_SUB_TITLE_HEIGHT + ABOUT_PAGE_SUB_TITLE_TOP)
#define		ABOUT_PAGE_TAB_INTRODUCE_LEFT			50
#define		ABOUT_PAGE_TAB_INTRODUCE_WIDTH			160
#define		ABOUT_PAGE_TAB_INTRODUCE_HEIGHT			40

#define		ABOUT_PAGE_TAB_OPEN_SOURCE_TOP			ABOUT_PAGE_TAB_INTRODUCE_TOP
#define		ABOUT_PAGE_TAB_OPEN_SOURCE_LEFT			(ABOUT_PAGE_TAB_INTRODUCE_LEFT + ABOUT_PAGE_TAB_INTRODUCE_WIDTH + ABOUT_PAGE_TAB_SPAN)
#define		ABOUT_PAGE_TAB_OPEN_SOURCE_WIDTH		234
#define		ABOUT_PAGE_TAB_OPEN_SOURCE_HEIGHT		ABOUT_PAGE_TAB_INTRODUCE_HEIGHT

#define		ABOUT_PAGE_TAB_VERSION_INFO_TOP			ABOUT_PAGE_TAB_INTRODUCE_TOP
#define		ABOUT_PAGE_TAB_VERSION_INFO_LEFT		(ABOUT_PAGE_TAB_INTRODUCE_LEFT + ABOUT_PAGE_TAB_INTRODUCE_WIDTH + ABOUT_PAGE_TAB_SPAN + ABOUT_PAGE_TAB_OPEN_SOURCE_WIDTH + ABOUT_PAGE_TAB_SPAN)
#define		ABOUT_PAGE_TAB_VERSION_INFO_WIDTH		240
#define		ABOUT_PAGE_TAB_VERSION_INFO_HEIGHT		ABOUT_PAGE_TAB_INTRODUCE_HEIGHT

#define		ABOUT_PAGE_SPLIT_LINE_TOP			(29 + ABOUT_PAGE_TAB_VERSION_INFO_TOP + ABOUT_PAGE_TAB_VERSION_INFO_HEIGHT)
#define		ABOUT_PAGE_SPLIT_LINE_LEFT			50
#define		ABOUT_PAGE_SPLIT_LINE_WIDTH			(WHITE_BG_WIDTH - ABOUT_PAGE_SPLIT_LINE_LEFT * 2)
#define		ABOUT_PAGE_SPLIT_LINE_HEIGHT		1

#define		ABOUT_PAGE_TAB_AREA_TOP				(ABOUT_PAGE_SPLIT_LINE_TOP + 5)
#define		ABOUT_PAGE_TAB_AREA_LEFT			10
#define		ABOUT_PAGE_TAB_AREA_WIDTH			(WHITE_BG_WIDTH - ABOUT_PAGE_TAB_AREA_LEFT * 2)
#define		ABOUT_PAGE_TAB_AREA_HEIGHT			1005

#define		ABOUT_PAGE_LIST_ITEM_HEIGHT			60

#define		TAB_CONTENT_WIDTH (ABOUT_PAGE_SPLIT_LINE_WIDTH - 20)

////////////////////////////////////////////About Page Version Tab////////////////////////////////////////////////
#define		ABOUT_PAGE_TAB_VER_LOGO_TOP			(386 + WHITE_BG_TOP)
#define		ABOUT_PAGE_TAB_VER_LOGO_LEFT		962		//calc
#define		ABOUT_PAGE_TAB_VER_LOGO_SIZE		295

#define		ABOUT_PAGE_TAB_VER_APP_NAME_TOP			(ABOUT_PAGE_TAB_VER_LOGO_TOP + ABOUT_PAGE_TAB_VER_LOGO_SIZE + 85)
//#define		ABOUT_PAGE_TAB_VER_APP_NAME_LEFT		962		//calc
#define		ABOUT_PAGE_TAB_VER_APP_NAME_WIDTH		300
#define		ABOUT_PAGE_TAB_VER_APP_NAME_HEIGHT		60

#define		ABOUT_PAGE_TAB_VER_VERSION_TOP			(ABOUT_PAGE_TAB_VER_APP_NAME_TOP + ABOUT_PAGE_TAB_VER_APP_NAME_HEIGHT + 85)
//#define		ABOUT_PAGE_TAB_VER_VERSION_LEFT		962		//calc
#define		ABOUT_PAGE_TAB_VER_VERSION_WIDTH		304
#define		ABOUT_PAGE_TAB_VER_VERSION_HEIGHT		35

#define		ABOUT_PAGE_TAB_COPYRIGHT_TOP			(ABOUT_PAGE_TAB_VER_VERSION_TOP + ABOUT_PAGE_TAB_VER_VERSION_HEIGHT + 47)
//#define		ABOUT_PAGE_TAB_VER_COPYRIGHT_LEFT		962		//calc
#define		ABOUT_PAGE_TAB_VER_COPYRIGHT_WIDTH		704
#define		ABOUT_PAGE_TAB_VER_COPYRIGHT_HEIGHT		35


#define		FONT_MESSAGE_BOX_TEXT			34
#define		FONT_LIST_TITLE_TEXT_SIZE		34
#define		FONT_LIST_ITEM_TEXT_SIZE		30


#endif