/**
Copyright (c) 2019-present Lenovo
Licensed under BSD-3, see COPYING.BSD file for details."
**/   

#include <Uefi.h>

#include <Library/DebugLib.h>
#include <Library/PcdLib.h>
#include <Library/UefiLib.h>

#include "okr.h"

//注意这个顺序和makezipres.bat的顺序是一样的
IMAGE_FILE_INFO g_Img_file_list[] = {
	
	{IMG_FILE_BACKGROUND_TITLE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BACKUP_TITLE,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_GOBACK,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_FOOT,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

    //{IMG_FILE_BTN_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    {IMG_FILE_BTN_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    {IMG_FILE_MOUSEA,		IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_CURSORTEXT,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_CURSORMOVE,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},

    {IMG_FILE_CURSORHAND,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_CANCELA,		IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
/*    {IMG_FILE_UPARROWA,		IMG_FILE_JPG_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_UPARROWB,		IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_DOWNARROWA,	IMG_FILE_JPG_LZ77, 0,	NULL,	NULL},

    {IMG_FILE_DOWNARROWB,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    */
	{IMG_FILE_PROC,			IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    //{IMG_FILE_BACKUPING,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
	//{IMG_FILE_FOOT_BACKUP,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
	//{IMG_FILE_FOOT_RESTORE,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},

//    {IMG_FILE_RESTORING,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_REMOVEDISK,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_HARDDISK,			IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    //{IMG_FILE_COMPLETE,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    //{IMG_FILE_BACKUP_COMPLETE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

    //{IMG_FILE_RESTORE_COMPLETE,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    //{IMG_FILE_DOWN,					IMG_FILE_JPG_LZ77,	0,	NULL,	NULL},
    //{IMG_FILE_PERCENT,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMG_FILE_BTN_BACKUP_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_BACKUP_FOCUS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_RESTORE_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_RESTORE_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{ IMG_FILE_BTN_BACKUP_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_RESTORE_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{IMG_FILE_BTN_BACKUP1_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_BACKUP1_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_RESTORE1_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_RESTORE1_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMG_FILE_BTN_DELETE_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_DELETE_FOCUS, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BTN_DELETE_DISABLE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMG_FILE_BUTTON_TEST,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BUTTON_TEST_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMG_FILE_BUTTON_CONFIRM_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BUTTON_GO_BACK_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMAG_FILE_TITLE_LENOVO_DRV_INSTALL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_TITLE_DRV_INSTALL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMAG_FILE_BK_DAI_SETTINGS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_FINISH,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_ERROR,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_COPYING,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_COMPLETE_FOCUS,  	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	{IMAG_FILE_INITIAL_BK,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_INITIAL_BK_SPACE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_INITIAL_BK_TXT,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMAG_FILE_EXIT_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_EXIT_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_VERSION_NORMAL,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_ERROR2,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_NEXT,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_NEXT_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},		

	{IMAG_FILE_SYS_BK_TITLE,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_SYS_R_TITLE,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_OK_DESC,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_R_OK_DESC,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	

	//{IMAG_FILE_BTN_DOWN,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BTN_DOWN_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BTN_UP,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BTN_UP_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	

	//{IMAG_FILE_COYPY_RIGHT,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_GOBACK_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	
	//{IMAG_FILE_CONFIRM_UNFOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	
	//{IMAG_FILE_BTN_RESTORE_DISABLE,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	

	//{IMAG_FILE_SYS_R_TIP_SELECT_BACKUP_POINT, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_SYS_R_TIP_CHECK_BACKUP_POINT,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{IMAG_FILE_TIP_USE_TIME, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_REMAIN_TIME,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{IMAG_FILE_TIP_BACKUP_SELECT_STORE_DEVICE, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_BACKUP_DATA_SIZE,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_BACKUP_MEMO, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_BACKUP_HOT_PNP, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMAG_FILE_BK_DAI_FINISH2, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
 
	//{ IMG_FILE_BUTTON_CANCEL_UNFOCUS , 		    IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_CANCEL_FOCUS , 		    IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{IMAG_FILE_COYPY_RIGHT_MINI,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{IMG_FILE_0,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_1,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_2,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_3,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_4,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_5,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_6,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_7,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_8,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   {IMG_FILE_9,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},

//	{ IMG_NEW_LINCENCE_PAGE_1,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_2,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_3,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_4,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_5,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_6,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
  //  { IMG_NEW_LINCENCE_PAGE_7,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_8,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_9,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
  
	//{ IMG_LINCENCE_BACK_01,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_BACK_02,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_BACK_03,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_NEXT_01,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_NEXT_02,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_NEXT_03,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_COMFM_01,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_COMFM_02,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_CLOSE_01,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	//{ IMG_LINCENCE_CLOSE_02,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
 
	//////////////////////////////////////////////////////////////////////////////////////

	//{ IMG_BUTTON_FORCE_RECOVERY_FOCUS, 		    IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_BUTTON_FORCE_RECOVERY_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	

	{ IMG_FILE_BTN_ABOUT_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_ABOUT_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_ABOUT_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BTN_EXIT_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_EXIT_FOCUS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_EXIT_PRESS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_LOGO, 					IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_ENQUIRE, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL }, //提示框，询问
	{ IMG_FILE_INFO,	 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL }, //提示框，提示
	{ IMG_FILE_WARNING, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL }, //提示框，警告

	{ IMG_FILE_MSG_CLOSE_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_MSG_CLOSE_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_MSG_CLOSE_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_MSG_SHUTDOWN_UNFOCUS, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_SHUTDOWN_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_SHUTDOWN_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_MSG_REBOOT_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_REBOOT_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_REBOOT_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BUTTON_CONFIRM_PRESS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_GO_BACK_PRESS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_CANCEL_PRESS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BTN_BACKUP1_PRESS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_RESTORE1_PRESS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_SUCCESS,					IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_PAGE_BG,					IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_WHITE_BG_LEFT_TOP,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_LEFT_BOTTOM,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_RIGHT_TOP,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_RIGHT_BOTTOM,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BTN_DELETE_PRESS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_NEXT_PRESS,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMAG_FILE_APP_LOGO,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMAG_FILE_ABOUT_INTRODUCE,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_INTRODUCE_FOCUS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_OPEN_SOU,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_OPEN_SOU_FOCUS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_VER,					IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_VER_FOCUS,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMAG_FILE_DISK_BG_NORMAL,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMAG_FILE_DISK_BG_SELECT,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_REMOVEDISK_SEL,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HARDDISK_SEL,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_PROGRESS_HEAD,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_TAIL,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_FRAME_HEAD,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_FRAME_TAIL,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BACKUP_POINT,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BACKUP_POINT_SEL,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_LOCK,						IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_LOCK_SEL,					IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_NEW_DISK,					IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_NEW_DISK_SEL,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_ORI_DISK,					IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_ORI_DISK_SEL,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_BUTTON_FORCE_RECOVERY_FRESS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_FAILED,						IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	////////small
	{ IMG_FILE_BTN_ABOUT_S_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_ABOUT_S_FOCUS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_ABOUT_S_PRESS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BUTTON_CANCEL_S_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_CANCEL_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_CANCEL_S_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BTN_DELETE_S_NORMAL, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_DELETE_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_DELETE_S_DISABLE, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_DELETE_S_PRESS, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_ENQUIRE_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_INFO_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WARNING_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BTN_EXIT_S_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_EXIT_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_EXIT_S_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BUTTON_GO_BACK_S_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_GO_BACK_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_GO_BACK_S_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMAG_FILE_INITIAL_BK_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_MSG_CLOSE_S_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_MSG_CLOSE_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_MSG_CLOSE_S_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMAG_FILE_NEXT_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_NEXT_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_NEXT_PRESS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_MSG_SHUTDOWN_S_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_SHUTDOWN_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_SHUTDOWN_S_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_SUCCESS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_FAILED_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	/*{ IMG_FILE_BUTTON_CANCEL_MAIN_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_CANCEL_MAIN_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_CANCEL_MAIN_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BUTTON_CANCEL_MAIN_S_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_CANCEL_MAIN_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_CANCEL_MAIN_S_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },*/

	//{ IMG_FILE_BUTTON_OK_SUB_UNFOCUS, IMG_FILE_BMP_LZ77, 0, NULL, NULL },
	//{ IMG_FILE_BUTTON_OK_SUB_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_OK_SUB_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BUTTON_OK_SUB_S_UNFOCUS, IMG_FILE_BMP_LZ77, 0, NULL, NULL },
	//{ IMG_FILE_BUTTON_OK_SUB_S_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_OK_SUB_S_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BTN_BACKUP_NORMAL_S, IMG_FILE_BMP_LZ77, 0, NULL, NULL },
	//{ IMG_FILE_BTN_BACKUP_FOCUS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_BACKUP_PRESS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BTN_RESTORE_NORMAL_S, IMG_FILE_BMP_LZ77, 0, NULL, NULL },
	//{ IMG_FILE_BTN_RESTORE_FOCUS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_RESTORE_PRESS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BACKGROUND_TITLE_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_LOGO_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMAG_FILE_ABOUT_INTRODUCE_S, IMG_FILE_BMP_LZ77, 0, NULL, NULL },
	//{ IMAG_FILE_ABOUT_INTRODUCE_FOCUS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_OPEN_SOU_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_OPEN_SOU_FOCUS_S, IMG_FILE_BMP_LZ77, 0, NULL, NULL },
	//{ IMAG_FILE_ABOUT_VER_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_ABOUT_VER_FOCUS_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BACKUP_POINT_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BACKUP_POINT_SEL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_HARDDISK_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HARDDISK_SEL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_FOOT_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_WHITE_BG_LEFT_TOP_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_LEFT_BOTTOM_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_RIGHT_TOP_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_RIGHT_BOTTOM_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_LOCK_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_LOCK_SEL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_NEW_DISK_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_NEW_DISK_SEL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_ORI_DISK_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_ORI_DISK_SEL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_PROGRESS_HEAD_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_TAIL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_FRAME_HEAD_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_FRAME_TAIL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMAG_FILE_SYS_BK_TITLE_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMAG_FILE_SYS_R_TITLE_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_REMOVEDISK_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_REMOVEDISK_SEL_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_L, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_R, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_L_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_M_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_R_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_L, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_R, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_L, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_R, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_L_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_M_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_R_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_L_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_M_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_R_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_L, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_R, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_L_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_M_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_R_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_MOUSEA_4K,		IMG_FILE_PCX_LZ77, 0,	NULL,	NULL },

	{ IMG_FILE_HOMEBTN_LT, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RT, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LB, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RB, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_TM, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_BM, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LM, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RM, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_BACKUP,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_RESTORE,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },

	{ IMG_FILE_HOMEBTN_LT_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RT_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LB_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RB_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_TM_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_BM_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LM_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RM_H, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_BACKUP_H,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_RESTORE_H,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },

	{ IMG_FILE_HOMEBTN_LT_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RT_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LB_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RB_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_TM_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_BM_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LM_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RM_P, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_BACKUP_P,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_RESTORE_P,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },

	{ IMG_FILE_HOMEBTN_LT_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RT_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LB_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RB_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_TM_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_BM_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LM_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RM_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_BACKUP_S,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_RESTORE_S,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },

	{ IMG_FILE_HOMEBTN_LT_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RT_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LB_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RB_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_TM_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_BM_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LM_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RM_H_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_BACKUP_H_S,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_RESTORE_H_S,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },

	{ IMG_FILE_HOMEBTN_LT_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RT_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LB_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RB_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_TM_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_BM_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_LM_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_RM_P_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_BACKUP_P_S,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_FILE_HOMEBTN_ICON_RESTORE_P_S,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },

	////////////////////for 2560*1440////////////////////////
	{ IMG_FILE_BTN_ABOUT_M_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_ABOUT_M_FOCUS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_ABOUT_M_PRESS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_ENQUIRE_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_INFO_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WARNING_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BTN_EXIT_M_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_EXIT_M_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTN_EXIT_M_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_SUCCESS_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_FAILED_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_FOOT_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BUTTON_GO_BACK_M_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_GO_BACK_M_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_GO_BACK_M_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMAG_FILE_INITIAL_BK_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_WHITE_BG_LEFT_TOP_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_LEFT_BOTTOM_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_RIGHT_TOP_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_WHITE_BG_RIGHT_BOTTOM_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_LOGO_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_MSG_CLOSE_M_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_MSG_CLOSE_M_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_MSG_CLOSE_M_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
		
	{ IMG_FILE_PROGRESS_HEAD_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_TAIL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_FRAME_HEAD_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_PROGRESS_FRAME_TAIL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BACKGROUND_TITLE_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMAG_FILE_SYS_BK_TITLE_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMAG_FILE_SYS_R_TITLE_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BACKUP_POINT_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BACKUP_POINT_SEL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_HARDDISK_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_HARDDISK_SEL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_LOCK_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_LOCK_SEL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_NEW_DISK_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_NEW_DISK_SEL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_ORI_DISK_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_ORI_DISK_SEL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_REMOVEDISK_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_REMOVEDISK_SEL_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_BTNSPL_L_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_M_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_R_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_L_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_M_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_F_R_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_L_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_M_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_P_R_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_L_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_M_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BTNSPL_D_R_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//	////////////////////for 1024*768////////////////////////
	//{ IMG_FILE_BTN_ABOUT_SS_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_ABOUT_SS_FOCUS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_ABOUT_SS_PRESS, 			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_ENQUIRE_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_INFO_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_WARNING_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BTN_EXIT_SS_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_EXIT_SS_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTN_EXIT_SS_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_SUCCESS_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_FAILED_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_FOOT_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BUTTON_GO_BACK_SS_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_GO_BACK_SS_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BUTTON_GO_BACK_SS_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMAG_FILE_INITIAL_BK_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_WHITE_BG_LEFT_TOP_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_WHITE_BG_LEFT_BOTTOM_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_WHITE_BG_RIGHT_TOP_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_WHITE_BG_RIGHT_BOTTOM_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_LOGO_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_MSG_CLOSE_SS_UNFOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_CLOSE_SS_FOCUS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_MSG_CLOSE_SS_PRESS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_PROGRESS_HEAD_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_PROGRESS_TAIL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_PROGRESS_FRAME_HEAD_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_PROGRESS_FRAME_TAIL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BACKGROUND_TITLE_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_SYS_BK_TITLE_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMAG_FILE_SYS_R_TITLE_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//	//{ IMG_FILE_BACKUP_POINT_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_BACKUP_POINT_SEL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_HARDDISK_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_HARDDISK_SEL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_LOCK_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_LOCK_SEL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_NEW_DISK_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_NEW_DISK_SEL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_ORI_DISK_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_ORI_DISK_SEL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_REMOVEDISK_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//	//{ IMG_FILE_REMOVEDISK_SEL_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMG_FILE_BTNSPL_L_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_M_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_R_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_F_L_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_F_M_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_F_R_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_P_L_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_P_M_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_P_R_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_D_L_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_D_M_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{ IMG_FILE_BTNSPL_D_R_SS, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMAG_FILE_APP_LOGO_S, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMAG_FILE_APP_LOGO_M, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{ IMG_FILE_FIND_BITLOCKER_KEY, 		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_FIND_BITLOCKER_KEY_M, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_FIND_BITLOCKER_KEY_S, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

    {0,0,0,NULL,NULL}
};


PIMAGE_FILE_INFO FindImgFileFromName(DWORD fileid)
{
	//MyLog(LOG_ERROR, L"FindImgFileFromName fileid: %d\n", fileid);
    INTN index;
    index = 0;
    while (g_Img_file_list[index].id != 0) {
        //if (!StrnCmp(g_Img_file_list[index].filename,name,10))
		if (g_Img_file_list[index].id == fileid)
		{
			//MyLog(LOG_ERROR, L"FindImgFileFromName success.fileid: %d\n", fileid);
			return &g_Img_file_list[index];
		}

        index++;
    }
	MyLog(LOG_ERROR, L"Does not find the image file data. FileID: %d\n", fileid);
    return NULL;
}

int IsExistImgFile(DWORD fileid)
{
	int iRet = 0;
	INTN index;
	index = 0;
	while (g_Img_file_list[index].id != 0) 
	{
		if (g_Img_file_list[index].id == fileid)
		{
			iRet = 1;
			break;
		}
		index++;
	}
	return iRet;
}