#include <Uefi.h>

#include <Library/DebugLib.h>
#include <Library/PcdLib.h>
#include <Library/UefiLib.h>

#include "okr.h"

//注意这个顺序和makezipres.bat的顺序是一样的
IMAGE_FILE_INFO g_Img_file_list[] = {
	
	{IMG_FILE_BACKGROUND_TITLE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BACKUP_TITLE,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_RESTORE_TITLE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_GOBACK,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_FOOT,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

    {IMG_FILE_BTN_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    {IMG_FILE_BTN_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    {IMG_FILE_MOUSEA,		IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_CURSORTEXT,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_CURSORMOVE,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},

    {IMG_FILE_CURSORHAND,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_CANCELA,		IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_UPARROWA,		IMG_FILE_JPG_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_UPARROWB,		IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_DOWNARROWA,	IMG_FILE_JPG_LZ77, 0,	NULL,	NULL},

    {IMG_FILE_DOWNARROWB,	IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_PROC,			IMG_FILE_PCX_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_BACKUPING,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
	{IMG_FILE_FOOT_BACKUP,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
	{IMG_FILE_FOOT_RESTORE,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},

    {IMG_FILE_RESTORING,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_REMOVEDISK,		IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_HARDDISK,			IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_COMPLETE,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    {IMG_FILE_BACKUP_COMPLETE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

    {IMG_FILE_RESTORE_COMPLETE,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
    {IMG_FILE_DOWN,					IMG_FILE_JPG_LZ77,	0,	NULL,	NULL},
    {IMG_FILE_PERCENT,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	{IMG_FILE_BTN_BACKUP_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_BACKUP_FOCUS,		IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_RESTORE_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_RESTORE_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	{IMG_FILE_BTN_BACKUP1_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_BACKUP1_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_RESTORE1_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_RESTORE1_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	{IMG_FILE_BTN_DELETE_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_DELETE_FOCUS, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BTN_DELETE_DISABLE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMG_FILE_BUTTON_TEST,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMG_FILE_BUTTON_TEST_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	{IMG_FILE_BUTTON_CONFIRM_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMG_FILE_BUTTON_GO_BACK_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMAG_FILE_TITLE_LENOVO_DRV_INSTALL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_TITLE_DRV_INSTALL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	//{IMAG_FILE_BK_DAI_SETTINGS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_FINISH,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_ERROR,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_COPYING,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_BK_COMPLETE_FOCUS,  	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	{IMAG_FILE_INITIAL_BK,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_INITIAL_BK_SPACE,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_INITIAL_BK_TXT,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},

	{IMAG_FILE_EXIT_FOCUS,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_EXIT_NORMAL,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_VERSION_NORMAL,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	//{IMAG_FILE_BK_DAI_ERROR2,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_NEXT,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_NEXT_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},		

	{IMAG_FILE_SYS_BK_TITLE,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_SYS_R_TITLE,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_BK_OK_DESC,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_R_OK_DESC,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	

	{IMAG_FILE_BTN_DOWN,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_BTN_DOWN_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_BTN_UP,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_BTN_UP_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	

	{IMAG_FILE_COYPY_RIGHT,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},
	{IMAG_FILE_GOBACK_FOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	
	{IMAG_FILE_CONFIRM_UNFOCUS,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	
	{IMAG_FILE_BTN_RESTORE_DISABLE,IMG_FILE_BMP_LZ77,	0,	NULL,	NULL},	

	//{IMAG_FILE_SYS_R_TIP_SELECT_BACKUP_POINT, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_SYS_R_TIP_CHECK_BACKUP_POINT,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{IMAG_FILE_TIP_USE_TIME, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_REMAIN_TIME,	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{IMAG_FILE_TIP_BACKUP_SELECT_STORE_DEVICE, 	IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_BACKUP_DATA_SIZE,			IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_BACKUP_MEMO, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	//{IMAG_FILE_TIP_BACKUP_HOT_PNP, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	//{ IMAG_FILE_BK_DAI_FINISH2, 				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
 
	{ IMG_FILE_BUTTON_CANCEL_FOCUS , 		    IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },
	{ IMG_FILE_BUTTON_CANCEL_UNFOCUS , 		    IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{IMAG_FILE_COYPY_RIGHT_MINI,				IMG_FILE_BMP_LZ77,	0,	NULL,	NULL },

	{IMG_FILE_0,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_1,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_2,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_3,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_4,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_5,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_6,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_7,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_8,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
    {IMG_FILE_9,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},

//	{ IMG_NEW_LINCENCE_PAGE_1,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_2,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_3,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_4,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_5,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_6,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
  //  { IMG_NEW_LINCENCE_PAGE_7,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_8,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
 //   { IMG_NEW_LINCENCE_PAGE_9,	IMG_FILE_BMP_LZ77, 0,	NULL,	NULL},
  
	{ IMG_LINCENCE_BACK_01,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_BACK_02,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_BACK_03,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_NEXT_01,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_NEXT_02,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_NEXT_03,	    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_COMFM_01,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_COMFM_02,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_CLOSE_01,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
	{ IMG_LINCENCE_CLOSE_02,    IMG_FILE_BMP_LZ77, 0,	NULL,	NULL },
 
    {0,0,0,NULL,NULL}
};

PIMAGE_FILE_INFO FindImgFileFromName(DWORD fileid)
{
    INTN index;
    index = 0;
    while (g_Img_file_list[index].id != 0) {
        //if (!StrnCmp(g_Img_file_list[index].filename,name,10))
       	if(g_Img_file_list[index].id == fileid)
            return &g_Img_file_list[index];
        index++;
    }
    return NULL;
}